version: '3.8'

services:
  fireflyqa:
    build: .
    container_name: fireflyqa
    restart: always
    ports:
      - "3010:3000"  # Use port 3010 externally; adjust as needed
    environment:
      - NODE_ENV=production
