name: Deploy fireflyqa.com

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_IP }}
        username: root
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          cd ~/sites/site1.com
          git pull origin main
          docker compose build
          docker compose down
          docker compose up -d
